### ISSUE TITLE
Generation fails with java.net.MalformedURLException: unknown protocol: maven since 0.14.0

### ISSUE THREAD

**Issue by tomdevroomen** [highsource/jaxb-tools#246] opened 2022-06-14 14:28 UTC
We have our xsds packed in jars and on version 0.13.3 works happily on Java 11.
Updating to 0.14.0 fails with `java.net.MalformedURLException: unknown protocol: maven`

Full stacktrace:
```
[ERROR] Error while parsing schema(s).Location [ maven:artifact:jar::!/xsd/my.xsd{4,92}].
org.xml.sax.SAXParseException: unknown protocol: maven
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.resolveRelativeURL (NGCCRuntimeEx.java:240)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.includeSchema (NGCCRuntimeEx.java:274)
    at com.sun.xml.xsom.impl.parser.state.includeDecl.action0 (includeDecl.java:83)
    at com.sun.xml.xsom.impl.parser.state.includeDecl.leaveElement (includeDecl.java:150)
    at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement (NGCCRuntime.java:319)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.util.SubtreeCutter.endElement (SubtreeCutter.java:112)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement (CustomizationContextChecker.java:199)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement (DOMForestScanner.java:140)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:255)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:281)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:250)
    at com.sun.xml.bind.unmarshaller.DOMScanner.scan (DOMScanner.java:127)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:92)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:100)
    at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse (DOMForestParser.java:104)
    at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse (ModelLoader.java:251)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity (NGCCRuntimeEx.java:381)
    at com.sun.xml.xsom.impl.parser.ParserContext.parse (ParserContext.java:128)
    at com.sun.xml.xsom.parser.XSOMParser.parse (XSOMParser.java:171)
    at com.sun.xml.xsom.parser.XSOMParser.parse (XSOMParser.java:160)
    at com.sun.tools.xjc.ModelLoader.createXSOM (ModelLoader.java:516)
    at com.sun.tools.xjc.ModelLoader.loadXMLSchema (ModelLoader.java:360)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:162)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:117)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.loadModel (XJC23Mojo.java:50)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute (XJC23Mojo.java:40)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute (XJC23Mojo.java:28)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute (RawXJC2Mojo.java:478)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute (RawXJC2Mojo.java:320)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.net.MalformedURLException: unknown protocol: maven
    at java.net.URL.<init> (URL.java:652)
    at java.net.URL.<init> (URL.java:541)
    at java.net.URL.<init> (URL.java:488)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.resolveRelativeURL (NGCCRuntimeEx.java:217)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.includeSchema (NGCCRuntimeEx.java:274)
    at com.sun.xml.xsom.impl.parser.state.includeDecl.action0 (includeDecl.java:83)
    at com.sun.xml.xsom.impl.parser.state.includeDecl.leaveElement (includeDecl.java:150)
    at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement (NGCCRuntime.java:319)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.util.SubtreeCutter.endElement (SubtreeCutter.java:112)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement (CustomizationContextChecker.java:199)
    at org.xml.sax.helpers.XMLFilterImpl.endElement (XMLFilterImpl.java:570)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement (DOMForestScanner.java:140)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:255)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:281)
    at com.sun.xml.bind.unmarshaller.DOMScanner.visit (DOMScanner.java:250)
    at com.sun.xml.bind.unmarshaller.DOMScanner.scan (DOMScanner.java:127)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:92)
    at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan (DOMForestScanner.java:100)
    at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse (DOMForestParser.java:104)
    at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse (ModelLoader.java:251)
    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity (NGCCRuntimeEx.java:381)
    at com.sun.xml.xsom.impl.parser.ParserContext.parse (ParserContext.java:128)
    at com.sun.xml.xsom.parser.XSOMParser.parse (XSOMParser.java:171)
    at com.sun.xml.xsom.parser.XSOMParser.parse (XSOMParser.java:160)
    at com.sun.tools.xjc.ModelLoader.createXSOM (ModelLoader.java:516)
    at com.sun.tools.xjc.ModelLoader.loadXMLSchema (ModelLoader.java:360)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:162)
    at com.sun.tools.xjc.ModelLoader.load (ModelLoader.java:117)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.loadModel (XJC23Mojo.java:50)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute (XJC23Mojo.java:40)
    at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute (XJC23Mojo.java:28)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute (RawXJC2Mojo.java:478)
    at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute (RawXJC2Mojo.java:320)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by michael-o** [comment] 2022-08-29 10:44
duplicate of #244

**Closed** 2023-08-14 17:31 UTC
