### ISSUE TITLE
readme is merge conflicted on checked - may be others?

### ISSUE THREAD

**Issue by hazendaz** [highsource/jaxb-tools#318] opened 2023-08-19 02:05 UTC
noticed the readme had merge conflict resolution never performed so it shows as a merge conflict.  Possibly there are others if readme got by that way.

**Comment by laurentschoelens** [comment] 2023-08-19 06:18
@hazendaz thanks for the quick issue.
It was seen and I'll fix it next monday in cleaning PR

**Comment by laurentschoelens** [comment] 2023-08-19 06:38
I can also tell you that it's the only file concerned by merging flags "unresolved"

**Comment by laurentschoelens** [comment] 2023-08-20 19:37
Duplicate of #316

**Comment by laurentschoelens** [comment] 2023-08-20 19:37
Change in progress

**Closed** 2023-08-24 22:39 UTC
Labels: bug, duplicate, documentation

**Comment by laurentschoelens** [comment] 2023-08-27 10:38
@hazendaz readme is up to date
We also try to get all wiki doc and old confluence highsource in this repo wiki before moving to asciidoc documentation
Feel free to notice us if you found something wrong in the documentation again (or somewhere else).
