### ISSUE TITLE
"com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null - Java 17 & Jakarta

### ISSUE THREAD

**Issue by lsotov** [highsource/jaxb-tools#207] opened 2022-02-01 23:08 UTC
Need some help with this issue, we are migrating to Java 17 and we are using the following config:
```     
 <plugin>
        <groupId>org.jvnet.jaxb2.maven2</groupId>
        <artifactId>maven-jaxb23-plugin</artifactId>
        <version>0.14.0</version>
        <dependencies>
          <!-- JAXB API -->
          <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>3.0.1</version>
          </dependency>
          <!-- JAXB reference implementation  -->
          <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>3.0.2</version>
          </dependency>
        </dependencies>
        <configuration>
          <schemaDirectory>src/main/resources</schemaDirectory>
            <args>
                <arg>-Xsetters</arg>
            </args>
            <plugins>
                <plugin>
                    <groupId>org.jvnet.jaxb2_commons</groupId>
                    <artifactId>jaxb2-basics</artifactId>
                    <version>0.12.0</version>
                </plugin>
            </plugins>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
But I'm getting this error:
`Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null`

I've added added glassfish as a dependency as suggested [here](https://github.com/highsource/maven-jaxb2-plugin/issues/201):
```
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.5</version>
</dependency>
```
And while that's fixing the null issue, the generated classes are being created with `javax.xml.bind` package so I'm getting this error:
```
package javax.xml.bind.annotation does not exist

```

Thanks in advance

**Comment by mattrpav** [comment] 2022-04-04 20:09
As part of Jakarta EE changes in v3.x the package namespace migrated from javax.xml -> jakarta.xml. This will be addressed in v3.0.0 of maven-jaxb-plugin

**Comment by dohorn** [comment] 2022-04-06 11:41
Having the exaxt same problem on Java 17 and Spring Boot 2.6. Is there any working configuration until 3.0.0 is released?

**Comment by SkySpiral7** [comment] 2022-06-10 19:33
This issue is a duplicate of https://github.com/highsource/maven-jaxb2-plugin/issues/204 however this issue is easier to read, has a clear answer, and was added to the 3.0.0 milestone. I'd vote to close the other one if I had any idea how to do that.

**Comment by ergules** [comment] 2023-03-03 07:01
I had the same problem a week ago, package name changes surely affects this issue but also some packages are removed from JDK including this reflect package causes errors too. Anyway jaxws-ri package contains all necessary libs as transitive dependency and resolved all dependency conflicts in my project.
I removed all jaxb (core, impl, api) dependencies since jaxws-ri contains all. If you don't need jakarta packages this will solve your problem too. 

<dependency>
	<groupId>com.sun.xml.ws</groupId>
	<artifactId>jaxws-ri</artifactId>
	<version>${jaxws-ri.version}</version>
</dependency>

**Comment by laurentschoelens** [comment] 2023-07-05 08:06
> Having the exact same problem on Java 17 and Spring Boot 2.6. Is there any workaround until v3.0.0 is released?

@dohorn : if you use SB 2.6, the last version of plugin (2.0.2) should solve your issue (I guess) cause we did update the plugins dependencies.
The v3 version of the plugin will use jakarta packages and will then be compatible with SB 3+ since they migrate to jakarta from v3 version too.

**Comment by mattrpav** [comment] 2023-09-14 03:16
#389

**Closed by mattrpav** 2023-09-14 03:16 UTC
Labels: maven-plugin, jakarta

**Comment by laurentschoelens** [comment] 2023-10-11 23:02
Hi everyone, @lsotov / @chpasha / @dohorn / @SkySpiral7 / @ergules 
In case you missed the info, v3 and v4 jaxb-maven-plugin had been released, based on jaxb v3 and v4.
Please check the [migration guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide) for guidance and feel free to come back if needed
